### ISSUE TITLE
Livereload Doesn't Reload Better_Errors gem Error Page

### ISSUE THREAD

**Issue by demisx** [johnbintz/rack-livereload#51]
Hi,
Livereload works fine except when an error page from better_errors gem is shown. When that happens, I need to manually hit Command+R to reload a page. I've already posted this on guard-livereload gem page, but then realized that reloading is handled via rack-livereload. Not sure where exactly to report this issue.

Thanks.

**Comment by gerrywastaken** [comment]
@johnbintz Any chance of getting this change into the Readme? Will submit a pull request if it's helpful.

**Comment by gerrywastaken** [comment]
Thank you @johnbintz :)

**Comment by lserman** [comment]
`Rack::Lock` is no longer used by Rails. Has anyone found a new solution?
